#!/usr/bin/python3

import pymysql

# 打开数据库连接
# db = pymysql.connect("127.0.0.1:13306","workhour","111111","jieyiworkhour" )
db= pymysql.connect(host="127.0.0.1",user="workhour",password="123",db="jieyiworkhour",port=13306)

# 使用 cursor() 方法创建一个游标对象 cursor
cursor = db.cursor()

# 使用 execute()  方法执行 SQL 查询
cursor.execute("SELECT  project_id,project_name FROM t_projectmng")

# 使用 fetchone() 方法获取单条数据.
data = cursor.fetchall()

# print ("Database version : %s " % data)
print (data)

# 关闭数据库连接
db.close()